/**
 * Seeded list of popular Indian actors & actresses
 * to enable instant search suggestions.
 */
export const POPULAR_ACTORS = [
  "Aamir Khan",
  "Abhishek Bachchan",
  "Aditi Rao Hydari",
  "Ajay Devgn",
  "Ajith Kumar",
  "Akshay Kumar",
  "Alia Bhatt",
  "Allu Arjun",
  "Amitabh Bachchan",
  "Anil Kapoor",
  "Anushka Sharma",
  "Anushka Shetty",
  "Arjun Rampal",
  "Asif Ali",
  "Ayushmann Khurrana",
  "Aishwarya Rai Bachchan",
  "Bobby Deol",
  "Chiranjeevi",
  "Darshan",
  "Deepika Padukone",
  "Dev Anand",
  "Dhanush",
  "Dharmendra",
  "Dileep",
  "Dilip Kumar",
  "Dulquer Salmaan",
  "Fahadh Faasil",
  "Hema Malini",
  "Hrithik Roshan",
  "Irrfan Khan",
  "Jajam Ravi",
  "Jaya Bachchan",
  "Jayaram",
  "John Abraham",
  "Jr. NTR",
  "Jyothika",
  "Kajal Aggarwal",
  "Kajol",
  "Kamal Haasan",
  "Kangana Ranaut",
  "Kareena Kapoor",
  "Karthi",
  "Kartik Aaryan",
  "Katrina Kaif",
  "Keerthy Suresh",
  "Kiara Advani",
  "Kriti Sanon",
  "Madhavan",
  "Madhuri Dixit",
  "Mahesh Babu",
  "Mammootty",
  "Manju Warrier",
  "Manoj Bajpayee",
  "Mithun Chakraborty",
  "Mohanlal",
  "N. T. Rama Rao",
  "Nagarjuna",
  "Nani",
  "Naseeruddin Shah",
  "Nayanthara",
  "Nivin Pauly",
  "Pankaj Tripathi",
  "Parvathy Thiruvothu",
  "Pawan Kalyan",
  "Pooja Hegde",
  "Prabhas",
  "Priyanka Chopra",
  "Prithviraj Sukumaran",
  "Puneeth Rajkumar",
  "Radhika Apte",
  "Radhika Pandit",
  "Raj B. Shetty",
  "Raj Kapoor",
  "Rajesh Khanna",
  "Rajinikanth",
  "Rajkummar Rao",
  "Rakshit Shetty",
  "Ram Charan",
  "Rana Daggubati",
  "Ranbir Kapoor",
  "Rani Mukerji",
  "Ranveer Singh",
  "Rashmika Mandanna",
  "Ravi Teja",
  "Rekha",
  "Rishi Kapoor",
  "Rishab Shetty",
  "Saif Ali Khan",
  "Sai Pallavi",
  "Salman Khan",
  "Samantha Ruth Prabhu",
  "Sanjay Dutt",
  "Shah Rukh Khan",
  "Shahid Kapoor",
  "Shankar Nag",
  "Sharwanand",
  "Shila Rajkumar",
  "Shiva Rajkumar",
  "Shobana",
  "Shraddha Kapoor",
  "Sidharth Malhotra",
  "Sivaji Ganesan",
  "Sivakarthikeyan",
  "Sonakshi Sinha",
  "Sonam Kapoor",
  "Sridevi",
  "Sudeep",
  "Suniel Shetty",
  "Suraaj",
  "Suresh Gopi",
  "Suriya",
  "Sushant Singh Rajput",
  "Tabu",
  "Taapsee Pannu",
  "Tiger Shroff",
  "Tovino Thomas",
  "Trisha Krishnan",
  "Urvashi",
  "Varun Dhawan",
  "Venkatesh",
  "Vicky Kaushal",
  "Vidya Balan",
  "Vijay",
  "Vijay Deverakonda",
  "Vijay Sethupathi",
  "Vikram",
  "Vishnuvardhan",
  "Yash"
];
